name: Hspa

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./frontend

      - name: Build application
        run: npm run build
        working-directory: ./frontend

      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: frontend/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: frontend/dist

      - name: Deploy to Firebase
        run: |
          cd frontend
          firebase deploy --only hosting --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
